plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

theme: jekyll-theme-tactile

title: Optimal Tour
description: Writing about Rust, embedded development, and the intersection of the two.
