remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
title: "Optimal Tour"
description: "A dumping ground for long-form thoughts I'd like to share"
url: "https://thenewwazoo.github.io"
